backend:
  name: git-gateway
  branch: main

# Uncomment when testing locally
# local_backend: true

media_folder: "public/images/blog"
public_folder: "/images/blog"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "Category", name: "category", widget: "select", options: ["Question Deep Dive", "Process Guide", "News", "Community Q&A"] }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Read Time", name: "readTime", widget: "string", default: "5 min read" }
      - { label: "Meta Description", name: "metaDescription", widget: "text" }
      - { label: "Featured Image", name: "featuredImage", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
